name: CI

on:
  pull_request:
  push:
    tags:
      - "**"
env:
  LLVM_VERSION: 21.1.3
  CMAKE_STATIC_LIBRARY_PREFIX: lib
  CMAKE_STATIC_LIBRARY_SUFFIX: .a

jobs:
  generate-config:
    runs-on: ubuntu-latest
    outputs:
      BUSTER_GITHUB_TARGETS: ${{ steps.generate-config.outputs.BUSTER_GITHUB_TARGETS }}
      BUSTER_CMAKE_BUILD_TYPES: ${{ steps.generate-config.outputs.BUSTER_CMAKE_BUILD_TYPES }}
      BUSTER_MACOS_AARCH64: ${{ steps.generate-config.outputs.BUSTER_MACOS_AARCH64 }}
      BUSTER_LINUX_AARCH64: ${{ steps.generate-config.outputs.BUSTER_LINUX_AARCH64 }}
      BUSTER_LINUX_X86_64: ${{ steps.generate-config.outputs.BUSTER_LINUX_X86_64 }}
      BUSTER_WINDOWS_X86_64: ${{ steps.generate-config.outputs.BUSTER_WINDOWS_X86_64 }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Generate config
        id: generate-config
        uses: birth-software/github-config@v10
        with:
          include_windows_aarch64: true
  build_llvm:
    needs: generate-config
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(needs.generate-config.outputs.BUSTER_GITHUB_TARGETS) }}
        CMAKE_BUILD_TYPE: [ Release ]
        BUSTER_LLVM_ENABLE_ASSERTIONS: [ ON, OFF ]
    runs-on: ${{ matrix.os }}
    env:
      BUSTER_MACOS_AARCH64: ${{ needs.generate-config.outputs.BUSTER_MACOS_AARCH64 }}
      BUSTER_LINUX_AARCH64: ${{ needs.generate-config.outputs.BUSTER_LINUX_AARCH64 }}
      BUSTER_LINUX_X86_64: ${{ needs.generate-config.outputs.BUSTER_LINUX_X86_64 }}
      BUSTER_WINDOWS_X86_64: ${{ needs.generate-config.outputs.BUSTER_WINDOWS_X86_64 }}
      BUSTER_LLVM_ENABLE_ASSERTIONS: ${{ matrix.BUSTER_LLVM_ENABLE_ASSERTIONS }}
    steps:
      - name: Maximize build space
        if: matrix.os == env.BUSTER_LINUX_X86_64 || matrix.os == env.BUSTER_LINUX_AARCH64
        uses: davidgmbb/remove-unwanted-software@master
        with:
          remove-android: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          remove-large-packages: 'true'
          remove-cached-tools: 'true'
          remove-swapfile: 'true'
      - uses: actions/checkout@v4
      - uses: birth-software/github-setup@v10
      - name: Build
        shell: bash
        env:
          CMAKE_BUILD_TYPE: ${{ matrix.CMAKE_BUILD_TYPE }}
          BUSTER_ENABLE_CLANG: true
        run: |
          ./build.sh
      - name: Upload LLVM artifact (7z)
        uses: actions/upload-artifact@v4
        with:
          # Name of the artifact to upload.
          # Optional. Default is 'artifact'
          name: ${{env.LLVM_BASENAME}}.7z
          # A file, directory or wildcard pattern that describes what to upload
          # Required.
          path: ${{env.LLVM_ASSET_BASE_PATH}}.7z
          compression-level: 9
          overwrite: true
          if-no-files-found: 'error'
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ${{env.LLVM_BASENAME}}.7z
  fix_llvm_windows_assertions:
    needs: build_llvm
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        BUSTER_ARCH: [ x86_64, aarch64 ]
        os: [ ubuntu-24.04-arm ]
    env:
      BUSTER_OS: windows
      CMAKE_BUILD_TYPE: Release
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        if: startsWith(github.ref, 'refs/tags/')
      - name: Fix
        if: startsWith(github.ref, 'refs/tags/')
        shell: bash
        env:
          BUSTER_ARCH: ${{ matrix.BUSTER_ARCH }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./fix_llvm_windows_assertions.sh
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ${{env.LLVM_BASENAME}}.7z
